# This workflow will install Python dependencies, run tests and lint.
# This initiates on every push or pull_request to develop, as well as on manual trigger.

# The python version can be specified using the workflow_dispatch input python-version.
# If not specified, it will be read from pyproject.toml.
# In case of missing pyproject.toml, it will default to 3.11.

name: Build, Lint, and Test

on:
  push:
    branches: [ "develop" ]

  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version' # Allow specific python version on workflow_dispatch
        required: false
        default: ''

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install toml for reading pyproject.toml
      run: pip install toml

    - name: Set Python version from workflow input or pyproject.toml
      id: python-version
      run: |
        if [[ "${{ github.event.inputs.python-version }}" != "" ]]; then
          PYTHON_VERSION="${{ github.event.inputs.python-version }}"
        else
          PYTHON_VERSION=$(python3 -c 'import toml; pyproject = toml.load("pyproject.toml"); print(pyproject.get("project", {}).get("requires-python", "3.11").strip(">="))')
        fi
        echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
        echo "version=$PYTHON_VERSION" >> $GITHUB_OUTPUT

    - name: Set up Python ${{ steps.python-version.outputs.version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.python-version.outputs.version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        poetry install

    - name: Lint with Ruff
      run: |
        ruff check . --exit-zero

    - name: Test with pytest
      run: |
        python -m pytest
